# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

testfunction <- function(x) {
    .Call('anRpackage_testfunction', PACKAGE = 'anRpackage', x)
}

testfunctionA <- function(x) {
    .Call('anRpackage_testfunctionA', PACKAGE = 'anRpackage', x)
}

testfunctionB <- function(x) {
    .Call('anRpackage_testfunctionB', PACKAGE = 'anRpackage', x)
}

